name: readiew
description: A new Flutter project.
version: 0.0.5+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.0.0
  font_awesome_flutter: ^9.1.0
  geolocator: ^7.2.0+1
  google_fonts: ^2.1.0
  intl: ^0.17.0
  page_transition: ^2.0.2
  timeago: ^3.1.0
  url_launcher: ^6.0.9
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  cloud_firestore: ^2.3.0
  location: ^4.3.0
  http: ^0.13.3
  google_sign_in: ^5.0.5


dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/