name: cadets_nearby
description: Stay in touch with cadets nearby you.
version: 0.9.2+0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.1.0
  font_awesome_flutter: ^9.1.0
  geolocator: ^7.4.0
  intl: ^0.17.0
  page_transition: ^2.0.2
  timeago: ^3.1.0
  url_launcher: ^6.0.9
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0
  location: ^4.3.0
  http: ^0.13.3
  google_sign_in: ^5.0.7
  flutter_spinkit: ^5.0.0
  bottom_navy_bar: ^6.0.0
  image_picker: ^0.8.3+2
  firebase_messaging: ^10.0.6
  flutter_local_notifications: ^8.1.1+1
  shared_preferences: ^2.0.7


dev_dependencies:

  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    
  fonts:
    - family: DMSans
      fonts:
        - asset: fonts/DMSans-Regular.ttf
        - asset: fonts/DMSans-Italic.ttf
          style: italic

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
