name: cadets_nearby
description: Stay in touch with cadets nearby you.
version: 0.3.0+0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.1.0
  font_awesome_flutter: ^9.1.0
  geolocator: ^7.4.0
  google_fonts: ^2.1.0
  intl: ^0.17.0
  page_transition: ^2.0.2
  timeago: ^3.1.0
  url_launcher: ^6.0.9
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0
  location: ^4.3.0
  http: ^0.13.3
  google_sign_in: ^5.0.7
  flutter_spinkit: ^5.0.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  bottom_navy_bar: ^6.0.0


dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/