name: cadets_nearby
description: Stay in touch with cadets nearby you.
version: 2.0.3+25

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  auto_size_text: ^3.0.0-nullsafety.0
  bottom_navy_bar: ^6.0.0
  cached_network_image: ^3.1.0
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  firebase_storage: ^11.0.10
  flutter:
    sdk: flutter
  flutter_local_notifications: ^14.0.0+1
  flutter_map: ^4.0.0
  flutter_spinkit: ^5.0.0
  font_awesome_flutter: ^10.1.0
  #google_mobile_ads: ^1.0.1
  google_sign_in: ^6.1.0
  http: ^0.13.3
  image_picker: ^0.8.3+2
  latlong2: ^0.8.1
  location: ^4.3.0
  package_info_plus: ^3.0.2
  page_transition: ^2.0.2
  provider: ^6.0.0
  qr_flutter: ^4.0.0
  shared_preferences: ^2.0.7
  timeago: ^3.1.0
  url_launcher: ^6.1.10
  # webview_flutter: ^2.0.13


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    
  fonts:
    - family: DMSans
      fonts:
        - asset: fonts/DMSans-Regular.ttf
        - asset: fonts/DMSans-Italic.ttf
          style: italic

flutter_icons:
  adaptive_icon_background: "#ffe6d5"
  adaptive_icon_foreground: "assets/images/icon_fg.png"
  android: "ic_launcher"
  min_sdk_android: 21
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  color: "#ff9955"
  color_dark: "#222222"
  image: assets/images/icon_splash.png
  image_dark: assets/images/icon_splash.png
  # To enable support for Android 12, set the following parameter to true.  Defaults to false.
  android12:
    image: assets/images/icon_fg.png
    image_dark: assets/images/icon_fg.png
    icon_background_color: "#ffe6d5"
    icon_background_color_dark: "#ffe6d5"
    color: "#ff9955"
    color_dark: "#222222"

